namespace AmesaBackend.Shared.Authentication.Cryptography
{
    public interface IAesEncryptor
    {
        /// <summary>
        /// Encrypts the input string using AES encryption algorithm.
        /// </summary>
        /// <param name="input"></param>
        /// <param name="saltKey">Salt generated by algorithm</param>
        /// <param name="providedSalt">Optional parameter if you want to use same salt for multiple inputs</param>
        /// <returns></returns>
        public string EncryptText(string input, out string saltKey, string providedSalt = "");

        public string DecryptText(string input, string saltKey);

        public bool IsDecrypt(string input, string saltKey);
    }
}

