version: '3.8'

services:
  amesa-backend:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=postgres;Database=amesa_lottery;Username=postgres;Password=password;Port=5432
      - REDIS_CONNECTION_STRING=redis:6379
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    networks:
      - amesa-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=amesa_lottery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - amesa-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - amesa-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@amesa.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - amesa-network

volumes:
  postgres_dev_data:

networks:
  amesa-network:
    driver: bridge
