version: '3.8'

services:
  amesa-backend:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - amesa-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=amesa_lottery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - amesa-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - amesa-network

volumes:
  postgres_data:

networks:
  amesa-network:
    driver: bridge
