name: Build and Deploy Backend

on:
  push:
    branches: [dev, stage]
  pull_request:
    branches: [main, dev, stage]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          dotnet restore AmesaBackend/AmesaBackend.csproj
          dotnet restore AmesaBackend.Tests/AmesaBackend.Tests.csproj

      - name: Build
        run: |
          dotnet build AmesaBackend/AmesaBackend.csproj --configuration Release --no-restore
          dotnet build AmesaBackend.Tests/AmesaBackend.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test AmesaBackend.Tests/AmesaBackend.Tests.csproj --configuration Release --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish AmesaBackend/AmesaBackend.csproj --configuration Release --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-files
          path: publish/

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-files
          path: publish/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: dev-${{ github.sha }}
        run: |
          echo "🐳 Building Docker image for dev environment..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./AmesaBackend
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:dev-latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/amesa-backend:latest-with-curl
          echo "📤 Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-latest
          docker push $ECR_REGISTRY/amesa-backend:latest-with-curl
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "✅ Docker image pushed successfully!"

      - name: Update ECS Task Definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: dev-${{ github.sha }}
        run: |
          echo "🔄 Updating ECS service for dev environment..."
          aws ecs update-service \
            --cluster ${{ secrets.DEV_ECS_CLUSTER }} \
            --service ${{ secrets.DEV_ECS_SERVICE }} \
            --force-new-deployment \
            --region eu-north-1
          echo "✅ ECS service updated successfully!"

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-files
          path: publish/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: stage-${{ github.sha }}
        run: |
          echo "🐳 Building Docker image for stage environment..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./AmesaBackend
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:stage-latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/amesa-backend:latest-with-curl
          echo "📤 Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:stage-latest
          docker push $ECR_REGISTRY/amesa-backend:latest-with-curl
          echo "✅ Docker image pushed successfully!"

      - name: Update ECS Task Definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: stage-${{ github.sha }}
        run: |
          echo "🔄 Updating ECS service for stage environment..."
          aws ecs update-service \
            --cluster ${{ secrets.STAGE_ECS_CLUSTER }} \
            --service ${{ secrets.STAGE_ECS_SERVICE }} \
            --force-new-deployment \
            --region eu-north-1
          echo "✅ ECS service updated successfully!"

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-files
          path: publish/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: prod-${{ github.sha }}
        run: |
          echo "🐳 Building Docker image for production environment..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./AmesaBackend
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:prod-latest
          echo "📤 Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:prod-latest
          echo "✅ Docker image pushed successfully!"

      - name: Update ECS Task Definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: amesabe
          IMAGE_TAG: prod-${{ github.sha }}
        run: |
          echo "🔄 Updating ECS service for production environment..."
          aws ecs update-service \
            --cluster ${{ secrets.PROD_ECS_CLUSTER }} \
            --service ${{ secrets.PROD_ECS_SERVICE }} \
            --force-new-deployment \
            --region eu-north-1
          echo "✅ ECS service updated successfully!"
